name: Deploy Level 2 to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "level2/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: level2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./level2/dist
          destination_dir: level2
          keep_files: true
